name: Feature Request
description: Suggest an idea or enhancement for Canvas Tools
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - jlouisbru
body:
  - type: markdown
    attributes:
      value: |
        # Canvas Tools Feature Request
        Thank you for taking the time to suggest a new feature! Your feedback helps make Canvas Tools better for all educators.
        
        Please fill out the form below with as much detail as possible.
  
  - type: dropdown
    id: feature_type
    attributes:
      label: Type of Feature
      description: What type of feature are you suggesting?
      options:
        - New functionality
        - Enhancement to existing feature
        - User interface improvement
        - Performance optimization
        - Integration with another service
        - Documentation improvement
        - Other (please specify below)
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of the challenge or limitation you're experiencing.
      placeholder: I'm always frustrated when trying to [...] because [...]
    validations:
      required: false
  
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see happen? Be as specific as possible.
      placeholder: The tool should have a way to [...]
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Are there any alternative solutions or features you've thought about?
      placeholder: I've tried working around this by [...]
    validations:
      required: false
  
  - type: dropdown
    id: user_role
    attributes:
      label: Your primary role
      description: This helps us understand how the feature would be used.
      options:
        - Teacher/Professor
        - Teaching Assistant
        - Administrator
        - Instructional Designer
        - IT Support
        - Student
        - Other
    validations:
      required: false
  
  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to your workflow?
      options:
        - Critical (I can't use the tool effectively without it)
        - High (Would significantly improve my experience)
        - Medium (Would be a nice addition)
        - Low (Just an idea I had)
    validations:
      required: false
  
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: This feature would help in scenarios like [...]
    validations:
      required: false
  
  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: If you'd like to discuss this feature further, you can leave your email or other contact information.
      placeholder: email@example.com
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our project's code of conduct
      options:
        - label: I agree to be respectful and constructive in my communication
          required: true
